# Generated by Django 3.0.4 on 2020-04-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='website',
            field=models.URLField(default='website', max_length=250),
        ),
    ]
