# Generated by Django 3.0.4 on 2020-04-10 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('future_projects', '0002_project_website'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
