# Generated by Django 3.0.4 on 2020-04-10 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('future_projects', '0004_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
