# Generated by Django 3.0.4 on 2020-04-10 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('future_projects', '0006_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='website',
        ),
    ]
