# Generated by Django 3.0.4 on 2020-04-11 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('future_projects', '0007_remove_project_website'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
