# Generated by Django 3.0.4 on 2020-07-30 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proid', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('proemail', models.EmailField(max_length=254)),
                ('procontact', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'professional',
            },
        ),
    ]
